apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: import-flow-bwce
  title: Import flow for BWCE projects
  description: Import existing BWCE projects into TIBCO Developer Hub
  tags:
    - import-flow
    - tibco
    - template
    - developer-hub
spec:
  owner: group:default/tibco-imported
  type: import-flow
